name: subsound
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  logging: ^1.0.2
  async_redux: ^16.0.0
  audio_service: ^0.18.7
#  just_audio:
#    git:
#      url: https://github.com/esiqveland/just_audio.git
#      ref: 'test_proxy_errors_2'
#      path: just_audio
  just_audio: ^0.9.28
  just_audio_libwinmedia: ^0.0.4+1
#  libwinmedia:
#    git:
#      url: 'https://github.com/esiqveland/libwinmedia.git'
#      ref: '18-linux-fix-volume'
#      path: 'flutter'
  cached_network_image: ^3.2.1
  flutter_sticky_header: ^0.6.4
  flutter_cache_manager: ^3.3.0
  uuid: ^3.0.6
  connectivity_plus: ^2.3.6+1
  sqflite_common_ffi: ^2.1.1+1
  sqflite: ^2.0.3+1
  we_slide: ^2.3.0
  flutter_slidable: ^2.0.0
  rxdart: ^0.27.5
  sentry_flutter: ^6.9.1
  libadwaita: ^1.2.5
  adwaita: ^0.5.2
#  bitsdojo_window: ">=0.1.1+1 <1.0.0"
  multi_window: ^0.2.0
  titlebar_buttons: ">=1.0.0 <2.0.0"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  test: ^1.21.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/emptycover.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

